post http://localhost:3001/api/notes
Content-Type: application/json

{ 
    "content": "VS Code REST Client",
    "important": true
}

###
get http://localhost:3001/api/notes/60a5ae5cb76cbe498f8052df
Content-Type: application/json

###
put http://localhost:3001/api/notes/60a5ae5cb76cbe498f8052df
Content-Type: application/json

{ 
    "content": "HTML is Easy",
    "important": false
}